export const REQUEST_TOKEN_FETCHING_DATA = 'REQUEST_TOKEN_FETCHING_DATA';
export const REQUEST_TOKEN_FETCHING_DATA_SUCCESS= 'REQUEST_TOKEN_FETCHING_DATA_SUCCESS';
export const REQUEST_TOKEN_FETCHING_DATA_FAILURE= 'REQUEST_TOKEN_FETCHING_DATA_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';